Tfar setter update
TaskForce47/TF47-client-mod pull request #26
Opened 2021-05-23 16:36 UTC by DeRampage

Works

Loading LR Settings sometimes bugs
```
Loading LR Radio Data at z\TF47\addons\TFAR_Setter\functions\fn_getRadioData.sqf:42
18:31:17 TFAR_Setter[DEBUG]: Loading LR Settings: [1,6.44077,["31","32","33","31.5","68.2","51.7","42.0","83.7","84.6","68.5"],1,"_bluefor",2,2,any,false,true] at z\TF47\addons\TFAR_Setter\functions\fn_loadLRSettings.sqf:30
18:31:17 TFAR_Setter[ERR]: Failed to save VLR Data [Expected: [1,6.44077,["31","32","33","31.5","68.2","51.7","42.0","83.7","84.6","68.5"],1,"_bluefor",2,2,any,false,true] || Result: [1,6.44077,["31","32","33","31.5","68.2","51.7","42.0","83.7","84.6","68.5"],1,"_bluefor",2,2,any,false,true]] at z\TF47\addons\TFAR_Setter\functions\fn_loadLRSettings.sqf:44
18:31:17 TFAR_Setter[DEBUG]: Loaded settings for SR LR with results: [0,1,-1] at z\TF47\addons\TFAR_Setter\functions\fn_loadAllSettings.sqf:43
```

does weird stuff on the Lib when opening the Self Interaction

```
18:32:58 Error in expression <layer) call TFAR_fnc_hasVehicleRadio))" && {[ACE_player, _target, ["isNotInside">
18:32:58   Error position: <&& {[ACE_player, _target, ["isNotInside">
18:32:58   Error &&: Typ Zeichenfolge, erwartet Bool
18:32:58  ➥ Context: 
18:32:58 	[] L1 ()
	[] L22 (z\ace\addons\interact_menu\functions\fnc_render.sqf)
	[] L28 (z\ace\addons\interact_menu\functions\fnc_render.sqf)
	[] L131 (z\ace\addons\interact_menu\functions\fnc_renderActionPoints.sqf)
	[] L155 (z\ace\addons\interact_menu\functions\fnc_renderActionPoints.sqf)
	[] L116 (z\ace\addons\interact_menu\functions\fnc_renderActionPoints.sqf)
	[] L114 (z\ace\addons\interact_menu\functions\fnc_renderActionPoints.sqf)
	[] L75 (z\ace\addons\interact_menu\functions\fnc_renderBaseMenu.sqf)
	[] L25 (z\ace\addons\common\functions\fnc_cachedCall.sqf)
	[] L26 (z\ace\addons\common\functions\fnc_cachedCall.sqf)
	[] L81 (z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf)
	[] L76 (z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf)
	[] L81 (z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf)
	[] L76 (z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf)
	[] L81 (z\ace\addons\interact_menu\functions\fnc_collectActiveActionTree.sqf)
	[] L
```

2021-05-23 16:38 UTC, DragonGER commented
erhöhe mal die Versionsnummer auf 0.3.2 https://github.com/TaskForce47/TF47-client-mod/blob/master/addons/main/script_version.hpp

2021-05-23 17:01 UTC, Desty84 approved these changes

2021-05-24 00:06 UTC, DeRampage commented
Müder Rampage ist Müde. Hab den Fehler gefunden.
Rdy to merge! @Desty84

2021-05-24 09:19 UTC, DragonGER commented
Kannst du noch das required addons attribute innerhalb der cfgfunctions rausnehmen?

2021-05-24 10:18 UTC, Desty84 commented
> Kannst du noch das required addons attribute innerhalb der cfgfunctions rausnehmen?

Uhm, das darf doch auf keinen Fall nach ACE oder CBA geladen werden?
Das benutzt functions draus?
oder ist das im TF Main schon drinnen?

2021-05-24 10:48 UTC, DragonGER reviewed
> > Kannst du noch das required addons attribute innerhalb der cfgfunctions rausnehmen?
> 
> Uhm, das darf doch auf keinen Fall nach ACE oder CBA geladen werden?
> Das benutzt functions draus?
> oder ist das im TF Main schon drinnen?

Die required addons unter cfgpatches muss schon noch da bleiben. 
Nur das requiredaddons Feld unter der class cfgfunctions gehört da nicht hin.

2021-05-24 10:48 UTC, NeutraleNull commented on addons/TFAR_Setter/config.cpp
>              requiredAddons[] = {"ace_interact_menu", "task_force_radio", "cba_settings"};
was macht das hier? Das muss nur ein der cfg patches bei der addon definition deklariert sein.

2021-05-24 10:51 UTC, Desty84 commented on addons/TFAR_Setter/config.cpp
>              requiredAddons[] = {"ace_interact_menu", "task_force_radio", "cba_settings"};
Ja gut, jz versteh ich was du meinst

2021-05-24 10:51 UTC, Desty84 requested changes

2021-05-24 10:51 UTC, Desty84 commented on addons/TFAR_Setter/config.cpp
> -        requiredAddons[] = {"ace_interact_menu", "task_force_radio", "cba_settings"};
rückgänig machen

2021-05-24 10:51 UTC, Desty84 commented on addons/TFAR_Setter/config.cpp
> -            requiredAddons[] = {"ace_interact_menu", "task_force_radio", "cba_settings"};
das passt so

2021-05-24 10:59 UTC, DeRampage commented on addons/TFAR_Setter/config.cpp
> -        requiredAddons[] = {"ace_interact_menu", "task_force_radio", "cba_settings"};
done

2021-05-24 11:11 UTC, DragonGER requested changes, later dismissed
Einfach die Zeile komplett löschen, dann sollte es ein für alle mal weg sein.

2021-05-24 11:11 UTC, DragonGER commented on addons/TFAR_Setter/config.cpp
> +            requiredAddons[] = {};
Es ist wieder da :D

2021-05-24 11:13 UTC, DeRampage commented on addons/TFAR_Setter/config.cpp
> +            requiredAddons[] = {};
Na was nun Destys schreibt rein damit
und du raus?

2021-05-24 11:15 UTC, Desty84 commented on addons/TFAR_Setter/config.cpp
> +            requiredAddons[] = {};
> das passt so - also, dass es entfernt wurde passt
Meinte doch, dass es hier passt, dass es entfernt wurde

2021-05-24 11:16 UTC, Desty84 approved these changes

2021-05-24 11:20 UTC, DeRampage commented
Let's build this sucker!

2021-05-24 11:26 UTC, merged