Qo l mods
TaskForce47/TF47-client-mod pull request #31
Opened 2021-05-29 20:55 UTC by DeRampage

Implemented a lot of mods.
started translation and structuring

2021-05-29 22:10 UTC, Desty84 requested changes
Check Paths ... marked 3, but seems like most BC stuff uses wrong pathes

2021-05-29 22:10 UTC, Desty84 commented on addons/BC_main/$PBOPREFIX$
> +z\bcdw\addons\main
Der Pfad schaut falsch aus

2021-05-29 22:10 UTC, Desty84 commented on addons/BC_main/functions/script_component.hpp
> +#include "\z\bcdw\addons\main\script_component.hpp"
Pfad, siehe oben

2021-05-29 22:10 UTC, Desty84 commented on addons/BC_wedge/$PBOPREFIX$
> +z\bcdw\addons\wedge
Pfad

2021-05-30 22:34 UTC, DeRampage commented on addons/BC_wedge/$PBOPREFIX$
> +z\bcdw\addons\wedge
done

2021-05-30 22:34 UTC, DeRampage commented on addons/BC_main/functions/script_component.hpp
> +#include "\z\bcdw\addons\main\script_component.hpp"
also done

2021-05-30 22:34 UTC, DeRampage commented on addons/BC_main/$PBOPREFIX$
> +z\bcdw\addons\main
totally fuckin done

2021-05-30 23:03 UTC, Desty84 approved these changes

2021-05-30 23:25 UTC, merged