TFAR Update
TaskForce47/TF47-client-mod pull request #56
Opened 2021-06-25 23:28 UTC by Desty84

2021-06-26 13:37 UTC, Desty84 commented
@DragonGER 
```
Clean
Checks         [00:00:00] [##############################] [25|25]
Prebuild       [00:00:01] [##############################] [25|25]
error: Failed to parse config `addons\TFARSetter\config.cpp`
    error at 533:11: expected one of `[a-zA-Z0-9_]`, `=`, `[`

error: Unable to build `addons\TFARSetter`
Press Enter to continue...:
```

Findest du was?

2021-06-26 15:34 UTC, DragonGER reviewed
Die macro includes sind durcheinander

2021-06-26 15:34 UTC, DragonGER commented on addons/TFARSetter/functions/script_component.hpp
> +#include "\z\TF47\addons\main\script_component.hpp"
verweist auf das falsche script component
muss auf "\z\TF47\addons\TFARSetter\script_component.hpp" zeigen

2021-06-26 15:37 UTC, DragonGER requested changes

2021-06-26 15:37 UTC, DragonGER commented on addons/TFARSetter/script_component.hpp
> +#include "\z\TF47\addons\main\script_macros.hpp"
hier auch "\z\TF47\addons\TFARSetter\script_macros.hpp"

2021-06-26 15:48 UTC, Desty84 commented
Thx @DragonGER

2021-06-27 13:41 UTC, merged

2021-06-27 13:42 UTC, DragonGER approved these changes